/// these tests are from chess.js test suite
///
/// @link https://github.com/jhlywa/chess.js/blob/master/__tests__/history.test.ts
#[cfg(test)]
pub mod history_test_chess_js {
    use crate::{
        WasmChess,
        helpers::tsify_structs::{ColorChar, MoveVerbose, SquareStr},
    };

    #[test]
    fn history() {
        let mut chess = WasmChess::new(None).unwrap();

        let final_fen = "4q2k/2r1r3/4PR1p/p1p5/P1Bp1Q1P/1P6/6P1/6K1 b - - 4 41";
        let moves = [
            "c4", "e6", "Nf3", "d5", "d4", "Nf6", "Nc3", "Be7", "Bg5", "O-O", "e3", "h6", "Bh4",
            "b6", "cxd5", "Nxd5", "Bxe7", "Qxe7", "Nxd5", "exd5", "Rc1", "Be6", "Qa4", "c5", "Qa3",
            "Rc8", "Bb5", "a6", "dxc5", "bxc5", "O-O", "Ra7", "Be2", "Nd7", "Nd4", "Qf8", "Nxe6",
            "fxe6", "e4", "d4", "f4", "Qe7", "e5", "Rb8", "Bc4", "Kh8", "Qh3", "Nf8", "b3", "a5",
            "f5", "exf5", "Rxf5", "Nh7", "Rcf1", "Qd8", "Qg3", "Re7", "h4", "Rbb7", "e6", "Rbc7",
            "Qe5", "Qe8", "a4", "Qd8", "R1f2", "Qe8", "R2f3", "Qd8", "Bd3", "Qe8", "Qe4", "Nf6",
            "Rxf6", "gxf6", "Rxf6", "Kg8", "Bc4", "Kh8", "Qf4",
        ];

        moves.iter().for_each(|m| {
            chess.make_move(m).unwrap();
        });

        pretty_assertions::assert_eq!(chess.fen(None), final_fen.to_string());

        let answer: Vec<MoveVerbose> = vec![
            MoveVerbose {
                color: ColorChar::W,
                piece: "p".to_string(),
                from: "c2".to_string(),
                to: "c4".to_string(),
                san: "c4".to_string(),
                lan: "c2c4".to_string(),
                before: "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1".to_string(),
                after: "rnbqkbnr/pppppppp/8/8/2P5/8/PP1PPPPP/RNBQKBNR b KQkq - 0 1".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::B,
                piece: "p".to_string(),
                from: "e7".to_string(),
                to: "e6".to_string(),
                san: "e6".to_string(),
                lan: "e7e6".to_string(),
                before: "rnbqkbnr/pppppppp/8/8/2P5/8/PP1PPPPP/RNBQKBNR b KQkq - 0 1".to_string(),
                after: "rnbqkbnr/pppp1ppp/4p3/8/2P5/8/PP1PPPPP/RNBQKBNR w KQkq - 0 2".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "n".to_string(),
                from: "g1".to_string(),
                to: "f3".to_string(),
                san: "Nf3".to_string(),
                lan: "g1f3".to_string(),
                before: "rnbqkbnr/pppp1ppp/4p3/8/2P5/8/PP1PPPPP/RNBQKBNR w KQkq - 0 2".to_string(),
                after: "rnbqkbnr/pppp1ppp/4p3/8/2P5/5N2/PP1PPPPP/RNBQKB1R b KQkq - 1 2".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::B,
                piece: "p".to_string(),
                from: "d7".to_string(),
                to: "d5".to_string(),
                san: "d5".to_string(),
                lan: "d7d5".to_string(),
                before: "rnbqkbnr/pppp1ppp/4p3/8/2P5/5N2/PP1PPPPP/RNBQKB1R b KQkq - 1 2"
                    .to_string(),
                after: "rnbqkbnr/ppp2ppp/4p3/3p4/2P5/5N2/PP1PPPPP/RNBQKB1R w KQkq - 0 3"
                    .to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "p".to_string(),
                from: "d2".to_string(),
                to: "d4".to_string(),
                san: "d4".to_string(),
                lan: "d2d4".to_string(),
                before: "rnbqkbnr/ppp2ppp/4p3/3p4/2P5/5N2/PP1PPPPP/RNBQKB1R w KQkq - 0 3"
                    .to_string(),
                after: "rnbqkbnr/ppp2ppp/4p3/3p4/2PP4/5N2/PP2PPPP/RNBQKB1R b KQkq - 0 3"
                    .to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::B,
                piece: "n".to_string(),
                from: "g8".to_string(),
                to: "f6".to_string(),
                san: "Nf6".to_string(),
                lan: "g8f6".to_string(),
                before: "rnbqkbnr/ppp2ppp/4p3/3p4/2PP4/5N2/PP2PPPP/RNBQKB1R b KQkq - 0 3"
                    .to_string(),
                after: "rnbqkb1r/ppp2ppp/4pn2/3p4/2PP4/5N2/PP2PPPP/RNBQKB1R w KQkq - 1 4"
                    .to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "n".to_string(),
                from: "b1".to_string(),
                to: "c3".to_string(),
                san: "Nc3".to_string(),
                lan: "b1c3".to_string(),
                before: "rnbqkb1r/ppp2ppp/4pn2/3p4/2PP4/5N2/PP2PPPP/RNBQKB1R w KQkq - 1 4"
                    .to_string(),
                after: "rnbqkb1r/ppp2ppp/4pn2/3p4/2PP4/2N2N2/PP2PPPP/R1BQKB1R b KQkq - 2 4"
                    .to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::B,
                piece: "b".to_string(),
                from: "f8".to_string(),
                to: "e7".to_string(),
                san: "Be7".to_string(),
                lan: "f8e7".to_string(),
                before: "rnbqkb1r/ppp2ppp/4pn2/3p4/2PP4/2N2N2/PP2PPPP/R1BQKB1R b KQkq - 2 4"
                    .to_string(),
                after: "rnbqk2r/ppp1bppp/4pn2/3p4/2PP4/2N2N2/PP2PPPP/R1BQKB1R w KQkq - 3 5"
                    .to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "b".to_string(),
                from: "c1".to_string(),
                to: "g5".to_string(),
                san: "Bg5".to_string(),
                lan: "c1g5".to_string(),
                before: "rnbqk2r/ppp1bppp/4pn2/3p4/2PP4/2N2N2/PP2PPPP/R1BQKB1R w KQkq - 3 5"
                    .to_string(),
                after: "rnbqk2r/ppp1bppp/4pn2/3p2B1/2PP4/2N2N2/PP2PPPP/R2QKB1R b KQkq - 4 5"
                    .to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::B,
                piece: "k".to_string(),
                from: "e8".to_string(),
                to: "h8".to_string(),
                san: "O-O".to_string(),
                // TODO: fix Chess960 discrepancy
                lan: "e8h8".to_string(),
                before: "rnbqk2r/ppp1bppp/4pn2/3p2B1/2PP4/2N2N2/PP2PPPP/R2QKB1R b KQkq - 4 5"
                    .to_string(),
                after: "rnbq1rk1/ppp1bppp/4pn2/3p2B1/2PP4/2N2N2/PP2PPPP/R2QKB1R w KQ - 5 6"
                    .to_string(),
                promotion: None,
                captured: None,
                is_castle: true,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "p".to_string(),
                from: "e2".to_string(),
                to: "e3".to_string(),
                san: "e3".to_string(),
                lan: "e2e3".to_string(),
                before: "rnbq1rk1/ppp1bppp/4pn2/3p2B1/2PP4/2N2N2/PP2PPPP/R2QKB1R w KQ - 5 6"
                    .to_string(),
                after: "rnbq1rk1/ppp1bppp/4pn2/3p2B1/2PP4/2N1PN2/PP3PPP/R2QKB1R b KQ - 0 6"
                    .to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::B,
                piece: "p".to_string(),
                from: "h7".to_string(),
                to: "h6".to_string(),
                san: "h6".to_string(),
                lan: "h7h6".to_string(),
                before: "rnbq1rk1/ppp1bppp/4pn2/3p2B1/2PP4/2N1PN2/PP3PPP/R2QKB1R b KQ - 0 6"
                    .to_string(),
                after: "rnbq1rk1/ppp1bpp1/4pn1p/3p2B1/2PP4/2N1PN2/PP3PPP/R2QKB1R w KQ - 0 7"
                    .to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "b".to_string(),
                from: "g5".to_string(),
                to: "h4".to_string(),
                san: "Bh4".to_string(),
                lan: "g5h4".to_string(),
                before: "rnbq1rk1/ppp1bpp1/4pn1p/3p2B1/2PP4/2N1PN2/PP3PPP/R2QKB1R w KQ - 0 7"
                    .to_string(),
                after: "rnbq1rk1/ppp1bpp1/4pn1p/3p4/2PP3B/2N1PN2/PP3PPP/R2QKB1R b KQ - 1 7"
                    .to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::B,
                piece: "p".to_string(),
                from: "b7".to_string(),
                to: "b6".to_string(),
                san: "b6".to_string(),
                lan: "b7b6".to_string(),
                before: "rnbq1rk1/ppp1bpp1/4pn1p/3p4/2PP3B/2N1PN2/PP3PPP/R2QKB1R b KQ - 1 7"
                    .to_string(),
                after: "rnbq1rk1/p1p1bpp1/1p2pn1p/3p4/2PP3B/2N1PN2/PP3PPP/R2QKB1R w KQ - 0 8"
                    .to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "p".to_string(),
                from: "c4".to_string(),
                to: "d5".to_string(),
                san: "cxd5".to_string(),
                lan: "c4d5".to_string(),
                before: "rnbq1rk1/p1p1bpp1/1p2pn1p/3p4/2PP3B/2N1PN2/PP3PPP/R2QKB1R w KQ - 0 8"
                    .to_string(),
                after: "rnbq1rk1/p1p1bpp1/1p2pn1p/3P4/3P3B/2N1PN2/PP3PPP/R2QKB1R b KQ - 0 8"
                    .to_string(),
                promotion: None,
                captured: Some("p".to_string()),
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::B,
                piece: "n".to_string(),
                from: "f6".to_string(),
                to: "d5".to_string(),
                san: "Nxd5".to_string(),
                lan: "f6d5".to_string(),
                before: "rnbq1rk1/p1p1bpp1/1p2pn1p/3P4/3P3B/2N1PN2/PP3PPP/R2QKB1R b KQ - 0 8"
                    .to_string(),
                after: "rnbq1rk1/p1p1bpp1/1p2p2p/3n4/3P3B/2N1PN2/PP3PPP/R2QKB1R w KQ - 0 9"
                    .to_string(),
                promotion: None,
                captured: Some("p".to_string()),
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "b".to_string(),
                from: "h4".to_string(),
                to: "e7".to_string(),
                san: "Bxe7".to_string(),
                lan: "h4e7".to_string(),
                before: "rnbq1rk1/p1p1bpp1/1p2p2p/3n4/3P3B/2N1PN2/PP3PPP/R2QKB1R w KQ - 0 9"
                    .to_string(),
                after: "rnbq1rk1/p1p1Bpp1/1p2p2p/3n4/3P4/2N1PN2/PP3PPP/R2QKB1R b KQ - 0 9"
                    .to_string(),
                promotion: None,
                captured: Some("b".to_string()),
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::B,
                piece: "q".to_string(),
                from: "d8".to_string(),
                to: "e7".to_string(),
                san: "Qxe7".to_string(),
                lan: "d8e7".to_string(),
                before: "rnbq1rk1/p1p1Bpp1/1p2p2p/3n4/3P4/2N1PN2/PP3PPP/R2QKB1R b KQ - 0 9"
                    .to_string(),
                after: "rnb2rk1/p1p1qpp1/1p2p2p/3n4/3P4/2N1PN2/PP3PPP/R2QKB1R w KQ - 0 10"
                    .to_string(),
                promotion: None,
                captured: Some("b".to_string()),
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "n".to_string(),
                from: "c3".to_string(),
                to: "d5".to_string(),
                san: "Nxd5".to_string(),
                lan: "c3d5".to_string(),
                before: "rnb2rk1/p1p1qpp1/1p2p2p/3n4/3P4/2N1PN2/PP3PPP/R2QKB1R w KQ - 0 10"
                    .to_string(),
                after: "rnb2rk1/p1p1qpp1/1p2p2p/3N4/3P4/4PN2/PP3PPP/R2QKB1R b KQ - 0 10"
                    .to_string(),
                promotion: None,
                captured: Some("n".to_string()),
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::B,
                piece: "p".to_string(),
                from: "e6".to_string(),
                to: "d5".to_string(),
                san: "exd5".to_string(),
                lan: "e6d5".to_string(),
                before: "rnb2rk1/p1p1qpp1/1p2p2p/3N4/3P4/4PN2/PP3PPP/R2QKB1R b KQ - 0 10"
                    .to_string(),
                after: "rnb2rk1/p1p1qpp1/1p5p/3p4/3P4/4PN2/PP3PPP/R2QKB1R w KQ - 0 11".to_string(),
                promotion: None,
                captured: Some("n".to_string()),
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "r".to_string(),
                from: "a1".to_string(),
                to: "c1".to_string(),
                san: "Rc1".to_string(),
                lan: "a1c1".to_string(),
                before: "rnb2rk1/p1p1qpp1/1p5p/3p4/3P4/4PN2/PP3PPP/R2QKB1R w KQ - 0 11".to_string(),
                after: "rnb2rk1/p1p1qpp1/1p5p/3p4/3P4/4PN2/PP3PPP/2RQKB1R b K - 1 11".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::B,
                piece: "b".to_string(),
                from: "c8".to_string(),
                to: "e6".to_string(),
                san: "Be6".to_string(),
                lan: "c8e6".to_string(),
                before: "rnb2rk1/p1p1qpp1/1p5p/3p4/3P4/4PN2/PP3PPP/2RQKB1R b K - 1 11".to_string(),
                after: "rn3rk1/p1p1qpp1/1p2b2p/3p4/3P4/4PN2/PP3PPP/2RQKB1R w K - 2 12".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "q".to_string(),
                from: "d1".to_string(),
                to: "a4".to_string(),
                san: "Qa4".to_string(),
                lan: "d1a4".to_string(),
                before: "rn3rk1/p1p1qpp1/1p2b2p/3p4/3P4/4PN2/PP3PPP/2RQKB1R w K - 2 12".to_string(),
                after: "rn3rk1/p1p1qpp1/1p2b2p/3p4/Q2P4/4PN2/PP3PPP/2R1KB1R b K - 3 12".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::B,
                piece: "p".to_string(),
                from: "c7".to_string(),
                to: "c5".to_string(),
                san: "c5".to_string(),
                lan: "c7c5".to_string(),
                before: "rn3rk1/p1p1qpp1/1p2b2p/3p4/Q2P4/4PN2/PP3PPP/2R1KB1R b K - 3 12"
                    .to_string(),
                after: "rn3rk1/p3qpp1/1p2b2p/2pp4/Q2P4/4PN2/PP3PPP/2R1KB1R w K - 0 13".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "q".to_string(),
                from: "a4".to_string(),
                to: "a3".to_string(),
                san: "Qa3".to_string(),
                lan: "a4a3".to_string(),
                before: "rn3rk1/p3qpp1/1p2b2p/2pp4/Q2P4/4PN2/PP3PPP/2R1KB1R w K - 0 13".to_string(),
                after: "rn3rk1/p3qpp1/1p2b2p/2pp4/3P4/Q3PN2/PP3PPP/2R1KB1R b K - 1 13".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::B,
                piece: "r".to_string(),
                from: "f8".to_string(),
                to: "c8".to_string(),
                san: "Rc8".to_string(),
                lan: "f8c8".to_string(),
                before: "rn3rk1/p3qpp1/1p2b2p/2pp4/3P4/Q3PN2/PP3PPP/2R1KB1R b K - 1 13".to_string(),
                after: "rnr3k1/p3qpp1/1p2b2p/2pp4/3P4/Q3PN2/PP3PPP/2R1KB1R w K - 2 14".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "b".to_string(),
                from: "f1".to_string(),
                to: "b5".to_string(),
                san: "Bb5".to_string(),
                lan: "f1b5".to_string(),
                before: "rnr3k1/p3qpp1/1p2b2p/2pp4/3P4/Q3PN2/PP3PPP/2R1KB1R w K - 2 14".to_string(),
                after: "rnr3k1/p3qpp1/1p2b2p/1Bpp4/3P4/Q3PN2/PP3PPP/2R1K2R b K - 3 14".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::B,
                piece: "p".to_string(),
                from: "a7".to_string(),
                to: "a6".to_string(),
                san: "a6".to_string(),
                lan: "a7a6".to_string(),
                before: "rnr3k1/p3qpp1/1p2b2p/1Bpp4/3P4/Q3PN2/PP3PPP/2R1K2R b K - 3 14".to_string(),
                after: "rnr3k1/4qpp1/pp2b2p/1Bpp4/3P4/Q3PN2/PP3PPP/2R1K2R w K - 0 15".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "p".to_string(),
                from: "d4".to_string(),
                to: "c5".to_string(),
                san: "dxc5".to_string(),
                lan: "d4c5".to_string(),
                before: "rnr3k1/4qpp1/pp2b2p/1Bpp4/3P4/Q3PN2/PP3PPP/2R1K2R w K - 0 15".to_string(),
                after: "rnr3k1/4qpp1/pp2b2p/1BPp4/8/Q3PN2/PP3PPP/2R1K2R b K - 0 15".to_string(),
                promotion: None,
                captured: Some("p".to_string()),
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::B,
                piece: "p".to_string(),
                from: "b6".to_string(),
                to: "c5".to_string(),
                san: "bxc5".to_string(),
                lan: "b6c5".to_string(),
                before: "rnr3k1/4qpp1/pp2b2p/1BPp4/8/Q3PN2/PP3PPP/2R1K2R b K - 0 15".to_string(),
                promotion: None,
                captured: Some("p".to_string()),
                is_castle: false,
                is_en_passant: false,
                after: "rnr3k1/4qpp1/p3b2p/1Bpp4/8/Q3PN2/PP3PPP/2R1K2R w K - 0 16".to_string(),
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "k".to_string(),
                from: "e1".to_string(),
                to: "h1".to_string(),
                san: "O-O".to_string(),
                // TODO: discrepancy because of Chess960 by default
                lan: "e1h1".to_string(),
                before: "rnr3k1/4qpp1/p3b2p/1Bpp4/8/Q3PN2/PP3PPP/2R1K2R w K - 0 16".to_string(),
                after: "rnr3k1/4qpp1/p3b2p/1Bpp4/8/Q3PN2/PP3PPP/2R2RK1 b - - 1 16".to_string(),
                promotion: None,
                captured: None,
                is_castle: true,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::B,
                piece: "r".to_string(),
                from: "a8".to_string(),
                to: "a7".to_string(),
                san: "Ra7".to_string(),
                lan: "a8a7".to_string(),
                before: "rnr3k1/4qpp1/p3b2p/1Bpp4/8/Q3PN2/PP3PPP/2R2RK1 b - - 1 16".to_string(),
                after: "1nr3k1/r3qpp1/p3b2p/1Bpp4/8/Q3PN2/PP3PPP/2R2RK1 w - - 2 17".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "b".to_string(),
                from: "b5".to_string(),
                to: "e2".to_string(),
                san: "Be2".to_string(),
                lan: "b5e2".to_string(),
                before: "1nr3k1/r3qpp1/p3b2p/1Bpp4/8/Q3PN2/PP3PPP/2R2RK1 w - - 2 17".to_string(),
                after: "1nr3k1/r3qpp1/p3b2p/2pp4/8/Q3PN2/PP2BPPP/2R2RK1 b - - 3 17".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::B,
                piece: "n".to_string(),
                from: "b8".to_string(),
                to: "d7".to_string(),
                san: "Nd7".to_string(),
                lan: "b8d7".to_string(),
                before: "1nr3k1/r3qpp1/p3b2p/2pp4/8/Q3PN2/PP2BPPP/2R2RK1 b - - 3 17".to_string(),
                after: "2r3k1/r2nqpp1/p3b2p/2pp4/8/Q3PN2/PP2BPPP/2R2RK1 w - - 4 18".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "n".to_string(),
                from: "f3".to_string(),
                to: "d4".to_string(),
                san: "Nd4".to_string(),
                lan: "f3d4".to_string(),
                before: "2r3k1/r2nqpp1/p3b2p/2pp4/8/Q3PN2/PP2BPPP/2R2RK1 w - - 4 18".to_string(),
                after: "2r3k1/r2nqpp1/p3b2p/2pp4/3N4/Q3P3/PP2BPPP/2R2RK1 b - - 5 18".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::B,
                piece: "q".to_string(),
                from: "e7".to_string(),
                to: "f8".to_string(),
                san: "Qf8".to_string(),
                lan: "e7f8".to_string(),
                before: "2r3k1/r2nqpp1/p3b2p/2pp4/3N4/Q3P3/PP2BPPP/2R2RK1 b - - 5 18".to_string(),
                after: "2r2qk1/r2n1pp1/p3b2p/2pp4/3N4/Q3P3/PP2BPPP/2R2RK1 w - - 6 19".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "n".to_string(),
                from: "d4".to_string(),
                to: "e6".to_string(),
                san: "Nxe6".to_string(),
                lan: "d4e6".to_string(),
                before: "2r2qk1/r2n1pp1/p3b2p/2pp4/3N4/Q3P3/PP2BPPP/2R2RK1 w - - 6 19".to_string(),
                promotion: None,
                captured: Some("b".to_string()),
                is_castle: false,
                is_en_passant: false,
                after: "2r2qk1/r2n1pp1/p3N2p/2pp4/8/Q3P3/PP2BPPP/2R2RK1 b - - 0 19".to_string(),
            },
            MoveVerbose {
                color: ColorChar::B,
                piece: "p".to_string(),
                from: "f7".to_string(),
                to: "e6".to_string(),
                san: "fxe6".to_string(),
                lan: "f7e6".to_string(),
                before: "2r2qk1/r2n1pp1/p3N2p/2pp4/8/Q3P3/PP2BPPP/2R2RK1 b - - 0 19".to_string(),
                promotion: None,
                captured: Some("n".to_string()),
                is_castle: false,
                is_en_passant: false,
                after: "2r2qk1/r2n2p1/p3p2p/2pp4/8/Q3P3/PP2BPPP/2R2RK1 w - - 0 20".to_string(),
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "p".to_string(),
                from: "e3".to_string(),
                to: "e4".to_string(),
                san: "e4".to_string(),
                lan: "e3e4".to_string(),
                before: "2r2qk1/r2n2p1/p3p2p/2pp4/8/Q3P3/PP2BPPP/2R2RK1 w - - 0 20".to_string(),
                after: "2r2qk1/r2n2p1/p3p2p/2pp4/4P3/Q7/PP2BPPP/2R2RK1 b - - 0 20".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::B,
                piece: "p".to_string(),
                from: "d5".to_string(),
                to: "d4".to_string(),
                san: "d4".to_string(),
                lan: "d5d4".to_string(),
                before: "2r2qk1/r2n2p1/p3p2p/2pp4/4P3/Q7/PP2BPPP/2R2RK1 b - - 0 20".to_string(),
                after: "2r2qk1/r2n2p1/p3p2p/2p5/3pP3/Q7/PP2BPPP/2R2RK1 w - - 0 21".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "p".to_string(),
                from: "f2".to_string(),
                to: "f4".to_string(),
                san: "f4".to_string(),
                lan: "f2f4".to_string(),
                before: "2r2qk1/r2n2p1/p3p2p/2p5/3pP3/Q7/PP2BPPP/2R2RK1 w - - 0 21".to_string(),
                after: "2r2qk1/r2n2p1/p3p2p/2p5/3pPP2/Q7/PP2B1PP/2R2RK1 b - - 0 21".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::B,
                piece: "q".to_string(),
                from: "f8".to_string(),
                to: "e7".to_string(),
                san: "Qe7".to_string(),
                lan: "f8e7".to_string(),
                before: "2r2qk1/r2n2p1/p3p2p/2p5/3pPP2/Q7/PP2B1PP/2R2RK1 b - - 0 21".to_string(),
                after: "2r3k1/r2nq1p1/p3p2p/2p5/3pPP2/Q7/PP2B1PP/2R2RK1 w - - 1 22".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "p".to_string(),
                from: "e4".to_string(),
                to: "e5".to_string(),
                san: "e5".to_string(),
                lan: "e4e5".to_string(),
                before: "2r3k1/r2nq1p1/p3p2p/2p5/3pPP2/Q7/PP2B1PP/2R2RK1 w - - 1 22".to_string(),
                after: "2r3k1/r2nq1p1/p3p2p/2p1P3/3p1P2/Q7/PP2B1PP/2R2RK1 b - - 0 22".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::B,
                piece: "r".to_string(),
                from: "c8".to_string(),
                to: "b8".to_string(),
                san: "Rb8".to_string(),
                lan: "c8b8".to_string(),
                before: "2r3k1/r2nq1p1/p3p2p/2p1P3/3p1P2/Q7/PP2B1PP/2R2RK1 b - - 0 22".to_string(),
                after: "1r4k1/r2nq1p1/p3p2p/2p1P3/3p1P2/Q7/PP2B1PP/2R2RK1 w - - 1 23".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "b".to_string(),
                from: "e2".to_string(),
                to: "c4".to_string(),
                san: "Bc4".to_string(),
                lan: "e2c4".to_string(),
                before: "1r4k1/r2nq1p1/p3p2p/2p1P3/3p1P2/Q7/PP2B1PP/2R2RK1 w - - 1 23".to_string(),
                after: "1r4k1/r2nq1p1/p3p2p/2p1P3/2Bp1P2/Q7/PP4PP/2R2RK1 b - - 2 23".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::B,
                piece: "k".to_string(),
                from: "g8".to_string(),
                to: "h8".to_string(),
                san: "Kh8".to_string(),
                lan: "g8h8".to_string(),
                before: "1r4k1/r2nq1p1/p3p2p/2p1P3/2Bp1P2/Q7/PP4PP/2R2RK1 b - - 2 23".to_string(),
                after: "1r5k/r2nq1p1/p3p2p/2p1P3/2Bp1P2/Q7/PP4PP/2R2RK1 w - - 3 24".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "q".to_string(),
                from: "a3".to_string(),
                to: "h3".to_string(),
                san: "Qh3".to_string(),
                lan: "a3h3".to_string(),
                before: "1r5k/r2nq1p1/p3p2p/2p1P3/2Bp1P2/Q7/PP4PP/2R2RK1 w - - 3 24".to_string(),
                after: "1r5k/r2nq1p1/p3p2p/2p1P3/2Bp1P2/7Q/PP4PP/2R2RK1 b - - 4 24".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::B,
                piece: "n".to_string(),
                from: "d7".to_string(),
                to: "f8".to_string(),
                san: "Nf8".to_string(),
                lan: "d7f8".to_string(),
                before: "1r5k/r2nq1p1/p3p2p/2p1P3/2Bp1P2/7Q/PP4PP/2R2RK1 b - - 4 24".to_string(),
                after: "1r3n1k/r3q1p1/p3p2p/2p1P3/2Bp1P2/7Q/PP4PP/2R2RK1 w - - 5 25".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "p".to_string(),
                from: "b2".to_string(),
                to: "b3".to_string(),
                san: "b3".to_string(),
                lan: "b2b3".to_string(),
                before: "1r3n1k/r3q1p1/p3p2p/2p1P3/2Bp1P2/7Q/PP4PP/2R2RK1 w - - 5 25".to_string(),
                after: "1r3n1k/r3q1p1/p3p2p/2p1P3/2Bp1P2/1P5Q/P5PP/2R2RK1 b - - 0 25".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::B,
                piece: "p".to_string(),
                from: "a6".to_string(),
                to: "a5".to_string(),
                san: "a5".to_string(),
                lan: "a6a5".to_string(),
                before: "1r3n1k/r3q1p1/p3p2p/2p1P3/2Bp1P2/1P5Q/P5PP/2R2RK1 b - - 0 25".to_string(),
                after: "1r3n1k/r3q1p1/4p2p/p1p1P3/2Bp1P2/1P5Q/P5PP/2R2RK1 w - - 0 26".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "p".to_string(),
                from: "f4".to_string(),
                to: "f5".to_string(),
                san: "f5".to_string(),
                lan: "f4f5".to_string(),
                before: "1r3n1k/r3q1p1/4p2p/p1p1P3/2Bp1P2/1P5Q/P5PP/2R2RK1 w - - 0 26".to_string(),
                after: "1r3n1k/r3q1p1/4p2p/p1p1PP2/2Bp4/1P5Q/P5PP/2R2RK1 b - - 0 26".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::B,
                piece: "p".to_string(),
                from: "e6".to_string(),
                to: "f5".to_string(),
                san: "exf5".to_string(),
                lan: "e6f5".to_string(),
                before: "1r3n1k/r3q1p1/4p2p/p1p1PP2/2Bp4/1P5Q/P5PP/2R2RK1 b - - 0 26".to_string(),
                promotion: None,
                captured: Some("p".to_string()),
                is_castle: false,
                is_en_passant: false,
                after: "1r3n1k/r3q1p1/7p/p1p1Pp2/2Bp4/1P5Q/P5PP/2R2RK1 w - - 0 27".to_string(),
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "r".to_string(),
                from: "f1".to_string(),
                to: "f5".to_string(),
                san: "Rxf5".to_string(),
                lan: "f1f5".to_string(),
                before: "1r3n1k/r3q1p1/7p/p1p1Pp2/2Bp4/1P5Q/P5PP/2R2RK1 w - - 0 27".to_string(),
                promotion: None,
                captured: Some("p".to_string()),
                is_castle: false,
                is_en_passant: false,
                after: "1r3n1k/r3q1p1/7p/p1p1PR2/2Bp4/1P5Q/P5PP/2R3K1 b - - 0 27".to_string(),
            },
            MoveVerbose {
                color: ColorChar::B,
                piece: "n".to_string(),
                from: "f8".to_string(),
                to: "h7".to_string(),
                san: "Nh7".to_string(),
                lan: "f8h7".to_string(),
                before: "1r3n1k/r3q1p1/7p/p1p1PR2/2Bp4/1P5Q/P5PP/2R3K1 b - - 0 27".to_string(),
                after: "1r5k/r3q1pn/7p/p1p1PR2/2Bp4/1P5Q/P5PP/2R3K1 w - - 1 28".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "r".to_string(),
                from: "c1".to_string(),
                to: "f1".to_string(),
                san: "Rcf1".to_string(),
                lan: "c1f1".to_string(),
                before: "1r5k/r3q1pn/7p/p1p1PR2/2Bp4/1P5Q/P5PP/2R3K1 w - - 1 28".to_string(),
                after: "1r5k/r3q1pn/7p/p1p1PR2/2Bp4/1P5Q/P5PP/5RK1 b - - 2 28".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::B,
                piece: "q".to_string(),
                from: "e7".to_string(),
                to: "d8".to_string(),
                san: "Qd8".to_string(),
                lan: "e7d8".to_string(),
                before: "1r5k/r3q1pn/7p/p1p1PR2/2Bp4/1P5Q/P5PP/5RK1 b - - 2 28".to_string(),
                after: "1r1q3k/r5pn/7p/p1p1PR2/2Bp4/1P5Q/P5PP/5RK1 w - - 3 29".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "q".to_string(),
                from: "h3".to_string(),
                to: "g3".to_string(),
                san: "Qg3".to_string(),
                lan: "h3g3".to_string(),
                before: "1r1q3k/r5pn/7p/p1p1PR2/2Bp4/1P5Q/P5PP/5RK1 w - - 3 29".to_string(),
                after: "1r1q3k/r5pn/7p/p1p1PR2/2Bp4/1P4Q1/P5PP/5RK1 b - - 4 29".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::B,
                piece: "r".to_string(),
                from: "a7".to_string(),
                to: "e7".to_string(),
                san: "Re7".to_string(),
                lan: "a7e7".to_string(),
                before: "1r1q3k/r5pn/7p/p1p1PR2/2Bp4/1P4Q1/P5PP/5RK1 b - - 4 29".to_string(),
                after: "1r1q3k/4r1pn/7p/p1p1PR2/2Bp4/1P4Q1/P5PP/5RK1 w - - 5 30".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "p".to_string(),
                from: "h2".to_string(),
                to: "h4".to_string(),
                san: "h4".to_string(),
                lan: "h2h4".to_string(),
                before: "1r1q3k/4r1pn/7p/p1p1PR2/2Bp4/1P4Q1/P5PP/5RK1 w - - 5 30".to_string(),
                after: "1r1q3k/4r1pn/7p/p1p1PR2/2Bp3P/1P4Q1/P5P1/5RK1 b - - 0 30".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::B,
                piece: "r".to_string(),
                from: "b8".to_string(),
                to: "b7".to_string(),
                san: "Rbb7".to_string(),
                lan: "b8b7".to_string(),
                before: "1r1q3k/4r1pn/7p/p1p1PR2/2Bp3P/1P4Q1/P5P1/5RK1 b - - 0 30".to_string(),
                after: "3q3k/1r2r1pn/7p/p1p1PR2/2Bp3P/1P4Q1/P5P1/5RK1 w - - 1 31".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "p".to_string(),
                from: "e5".to_string(),
                to: "e6".to_string(),
                san: "e6".to_string(),
                lan: "e5e6".to_string(),
                before: "3q3k/1r2r1pn/7p/p1p1PR2/2Bp3P/1P4Q1/P5P1/5RK1 w - - 1 31".to_string(),
                after: "3q3k/1r2r1pn/4P2p/p1p2R2/2Bp3P/1P4Q1/P5P1/5RK1 b - - 0 31".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::B,
                piece: "r".to_string(),
                from: "b7".to_string(),
                to: "c7".to_string(),
                san: "Rbc7".to_string(),
                lan: "b7c7".to_string(),
                before: "3q3k/1r2r1pn/4P2p/p1p2R2/2Bp3P/1P4Q1/P5P1/5RK1 b - - 0 31".to_string(),
                after: "3q3k/2r1r1pn/4P2p/p1p2R2/2Bp3P/1P4Q1/P5P1/5RK1 w - - 1 32".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "q".to_string(),
                from: "g3".to_string(),
                to: "e5".to_string(),
                san: "Qe5".to_string(),
                lan: "g3e5".to_string(),
                before: "3q3k/2r1r1pn/4P2p/p1p2R2/2Bp3P/1P4Q1/P5P1/5RK1 w - - 1 32".to_string(),
                after: "3q3k/2r1r1pn/4P2p/p1p1QR2/2Bp3P/1P6/P5P1/5RK1 b - - 2 32".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::B,
                piece: "q".to_string(),
                from: "d8".to_string(),
                to: "e8".to_string(),
                san: "Qe8".to_string(),
                lan: "d8e8".to_string(),
                before: "3q3k/2r1r1pn/4P2p/p1p1QR2/2Bp3P/1P6/P5P1/5RK1 b - - 2 32".to_string(),
                after: "4q2k/2r1r1pn/4P2p/p1p1QR2/2Bp3P/1P6/P5P1/5RK1 w - - 3 33".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "p".to_string(),
                from: "a2".to_string(),
                to: "a4".to_string(),
                san: "a4".to_string(),
                lan: "a2a4".to_string(),
                before: "4q2k/2r1r1pn/4P2p/p1p1QR2/2Bp3P/1P6/P5P1/5RK1 w - - 3 33".to_string(),
                after: "4q2k/2r1r1pn/4P2p/p1p1QR2/P1Bp3P/1P6/6P1/5RK1 b - - 0 33".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::B,
                piece: "q".to_string(),
                from: "e8".to_string(),
                to: "d8".to_string(),
                san: "Qd8".to_string(),
                lan: "e8d8".to_string(),
                before: "4q2k/2r1r1pn/4P2p/p1p1QR2/P1Bp3P/1P6/6P1/5RK1 b - - 0 33".to_string(),
                after: "3q3k/2r1r1pn/4P2p/p1p1QR2/P1Bp3P/1P6/6P1/5RK1 w - - 1 34".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "r".to_string(),
                from: "f1".to_string(),
                to: "f2".to_string(),
                san: "R1f2".to_string(),
                lan: "f1f2".to_string(),
                before: "3q3k/2r1r1pn/4P2p/p1p1QR2/P1Bp3P/1P6/6P1/5RK1 w - - 1 34".to_string(),
                after: "3q3k/2r1r1pn/4P2p/p1p1QR2/P1Bp3P/1P6/5RP1/6K1 b - - 2 34".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::B,
                piece: "q".to_string(),
                from: "d8".to_string(),
                to: "e8".to_string(),
                san: "Qe8".to_string(),
                lan: "d8e8".to_string(),
                before: "3q3k/2r1r1pn/4P2p/p1p1QR2/P1Bp3P/1P6/5RP1/6K1 b - - 2 34".to_string(),
                after: "4q2k/2r1r1pn/4P2p/p1p1QR2/P1Bp3P/1P6/5RP1/6K1 w - - 3 35".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "r".to_string(),
                from: "f2".to_string(),
                to: "f3".to_string(),
                san: "R2f3".to_string(),
                lan: "f2f3".to_string(),
                before: "4q2k/2r1r1pn/4P2p/p1p1QR2/P1Bp3P/1P6/5RP1/6K1 w - - 3 35".to_string(),
                after: "4q2k/2r1r1pn/4P2p/p1p1QR2/P1Bp3P/1P3R2/6P1/6K1 b - - 4 35".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::B,
                piece: "q".to_string(),
                from: "e8".to_string(),
                to: "d8".to_string(),
                san: "Qd8".to_string(),
                lan: "e8d8".to_string(),
                before: "4q2k/2r1r1pn/4P2p/p1p1QR2/P1Bp3P/1P3R2/6P1/6K1 b - - 4 35".to_string(),
                after: "3q3k/2r1r1pn/4P2p/p1p1QR2/P1Bp3P/1P3R2/6P1/6K1 w - - 5 36".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "b".to_string(),
                from: "c4".to_string(),
                to: "d3".to_string(),
                san: "Bd3".to_string(),
                lan: "c4d3".to_string(),
                before: "3q3k/2r1r1pn/4P2p/p1p1QR2/P1Bp3P/1P3R2/6P1/6K1 w - - 5 36".to_string(),
                after: "3q3k/2r1r1pn/4P2p/p1p1QR2/P2p3P/1P1B1R2/6P1/6K1 b - - 6 36".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::B,
                piece: "q".to_string(),
                from: "d8".to_string(),
                to: "e8".to_string(),
                san: "Qe8".to_string(),
                lan: "d8e8".to_string(),
                before: "3q3k/2r1r1pn/4P2p/p1p1QR2/P2p3P/1P1B1R2/6P1/6K1 b - - 6 36".to_string(),
                after: "4q2k/2r1r1pn/4P2p/p1p1QR2/P2p3P/1P1B1R2/6P1/6K1 w - - 7 37".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "q".to_string(),
                from: "e5".to_string(),
                to: "e4".to_string(),
                san: "Qe4".to_string(),
                lan: "e5e4".to_string(),
                before: "4q2k/2r1r1pn/4P2p/p1p1QR2/P2p3P/1P1B1R2/6P1/6K1 w - - 7 37".to_string(),
                after: "4q2k/2r1r1pn/4P2p/p1p2R2/P2pQ2P/1P1B1R2/6P1/6K1 b - - 8 37".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::B,
                piece: "n".to_string(),
                from: "h7".to_string(),
                to: "f6".to_string(),
                san: "Nf6".to_string(),
                lan: "h7f6".to_string(),
                before: "4q2k/2r1r1pn/4P2p/p1p2R2/P2pQ2P/1P1B1R2/6P1/6K1 b - - 8 37".to_string(),
                after: "4q2k/2r1r1p1/4Pn1p/p1p2R2/P2pQ2P/1P1B1R2/6P1/6K1 w - - 9 38".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "r".to_string(),
                from: "f5".to_string(),
                to: "f6".to_string(),
                san: "Rxf6".to_string(),
                lan: "f5f6".to_string(),
                before: "4q2k/2r1r1p1/4Pn1p/p1p2R2/P2pQ2P/1P1B1R2/6P1/6K1 w - - 9 38".to_string(),
                promotion: None,
                captured: Some("n".to_string()),
                is_castle: false,
                is_en_passant: false,
                after: "4q2k/2r1r1p1/4PR1p/p1p5/P2pQ2P/1P1B1R2/6P1/6K1 b - - 0 38".to_string(),
            },
            MoveVerbose {
                color: ColorChar::B,
                piece: "p".to_string(),
                from: "g7".to_string(),
                to: "f6".to_string(),
                san: "gxf6".to_string(),
                lan: "g7f6".to_string(),
                before: "4q2k/2r1r1p1/4PR1p/p1p5/P2pQ2P/1P1B1R2/6P1/6K1 b - - 0 38".to_string(),
                promotion: None,
                captured: Some("r".to_string()),
                is_castle: false,
                is_en_passant: false,
                after: "4q2k/2r1r3/4Pp1p/p1p5/P2pQ2P/1P1B1R2/6P1/6K1 w - - 0 39".to_string(),
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "r".to_string(),
                from: "f3".to_string(),
                to: "f6".to_string(),
                san: "Rxf6".to_string(),
                lan: "f3f6".to_string(),
                before: "4q2k/2r1r3/4Pp1p/p1p5/P2pQ2P/1P1B1R2/6P1/6K1 w - - 0 39".to_string(),
                promotion: None,
                captured: Some("p".to_string()),
                is_castle: false,
                is_en_passant: false,
                after: "4q2k/2r1r3/4PR1p/p1p5/P2pQ2P/1P1B4/6P1/6K1 b - - 0 39".to_string(),
            },
            MoveVerbose {
                color: ColorChar::B,
                piece: "k".to_string(),
                from: "h8".to_string(),
                to: "g8".to_string(),
                san: "Kg8".to_string(),
                lan: "h8g8".to_string(),
                before: "4q2k/2r1r3/4PR1p/p1p5/P2pQ2P/1P1B4/6P1/6K1 b - - 0 39".to_string(),
                after: "4q1k1/2r1r3/4PR1p/p1p5/P2pQ2P/1P1B4/6P1/6K1 w - - 1 40".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "b".to_string(),
                from: "d3".to_string(),
                to: "c4".to_string(),
                san: "Bc4".to_string(),
                lan: "d3c4".to_string(),
                before: "4q1k1/2r1r3/4PR1p/p1p5/P2pQ2P/1P1B4/6P1/6K1 w - - 1 40".to_string(),
                after: "4q1k1/2r1r3/4PR1p/p1p5/P1BpQ2P/1P6/6P1/6K1 b - - 2 40".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::B,
                piece: "k".to_string(),
                from: "g8".to_string(),
                to: "h8".to_string(),
                san: "Kh8".to_string(),
                lan: "g8h8".to_string(),
                before: "4q1k1/2r1r3/4PR1p/p1p5/P1BpQ2P/1P6/6P1/6K1 b - - 2 40".to_string(),
                after: "4q2k/2r1r3/4PR1p/p1p5/P1BpQ2P/1P6/6P1/6K1 w - - 3 41".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "q".to_string(),
                from: "e4".to_string(),
                to: "f4".to_string(),
                san: "Qf4".to_string(),
                lan: "e4f4".to_string(),
                before: "4q2k/2r1r3/4PR1p/p1p5/P1BpQ2P/1P6/6P1/6K1 w - - 3 41".to_string(),
                after: "4q2k/2r1r3/4PR1p/p1p5/P1Bp1Q1P/1P6/6P1/6K1 b - - 4 41".to_string(),
                promotion: None,
                captured: None,
                is_castle: false,
                is_en_passant: false,
            },
        ];

        let history = chess.history_verbose();

        let history_san = chess.history_san();
        let history_lan = chess.history_uci();

        pretty_assertions::assert_eq!(moves.len(), history.len());
        pretty_assertions::assert_eq!(answer.len(), history.len());

        pretty_assertions::assert_eq!(answer, history);

        answer.iter().enumerate().for_each(|(i, el)| {
            pretty_assertions::assert_eq!(history_san[i], el.san);
            pretty_assertions::assert_eq!(history_lan[i], el.lan);
        });
    }

    #[test]
    fn history_pgn_setup() {
        let pgn = r#"[SetUp "1"]
[FEN "r1bqk1nr/pppp1ppp/2n5/4p3/1bB1P3/2P2N2/P2P1PPP/RNBQK2R b KQkq - 0 1"]

1. ... Ba5 2. O-O d6
3. d4"#;

        let mut chess = WasmChess::new(None).unwrap();

        chess.load_pgn(pgn).unwrap();

        let moves = vec![
            MoveVerbose {
                color: ColorChar::B,
                piece: "b".to_string(),
                from: SquareStr::B4.to_string(),
                to: SquareStr::A5.to_string(),
                lan: "b4a5".to_string(),
                san: "Ba5".to_string(),
                before: "r1bqk1nr/pppp1ppp/2n5/4p3/1bB1P3/2P2N2/P2P1PPP/RNBQK2R b KQkq - 0 1"
                    .to_string(),
                after: "r1bqk1nr/pppp1ppp/2n5/b3p3/2B1P3/2P2N2/P2P1PPP/RNBQK2R w KQkq - 1 2"
                    .to_string(),
                is_castle: false,
                is_en_passant: false,
                captured: None,
                promotion: None,
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "k".to_string(),
                from: SquareStr::E1.to_string(),
                to: SquareStr::H1.to_string(),
                lan: "e1h1".to_string(),
                san: "O-O".to_string(),
                before: "r1bqk1nr/pppp1ppp/2n5/b3p3/2B1P3/2P2N2/P2P1PPP/RNBQK2R w KQkq - 1 2"
                    .to_string(),
                after: "r1bqk1nr/pppp1ppp/2n5/b3p3/2B1P3/2P2N2/P2P1PPP/RNBQ1RK1 b kq - 2 2"
                    .to_string(),
                is_castle: true,
                is_en_passant: false,
                captured: None,
                promotion: None,
            },
            MoveVerbose {
                color: ColorChar::B,
                piece: "p".to_string(),
                from: SquareStr::D7.to_string(),
                to: SquareStr::D6.to_string(),
                lan: "d7d6".to_string(),
                san: "d6".to_string(),
                before: "r1bqk1nr/pppp1ppp/2n5/b3p3/2B1P3/2P2N2/P2P1PPP/RNBQ1RK1 b kq - 2 2"
                    .to_string(),
                after: "r1bqk1nr/ppp2ppp/2np4/b3p3/2B1P3/2P2N2/P2P1PPP/RNBQ1RK1 w kq - 0 3"
                    .to_string(),
                is_castle: false,
                is_en_passant: false,
                captured: None,
                promotion: None,
            },
            MoveVerbose {
                color: ColorChar::W,
                piece: "p".to_string(),
                from: SquareStr::D2.to_string(),
                to: SquareStr::D4.to_string(),
                lan: "d2d4".to_string(),
                san: "d4".to_string(),
                before: "r1bqk1nr/ppp2ppp/2np4/b3p3/2B1P3/2P2N2/P2P1PPP/RNBQ1RK1 w kq - 0 3"
                    .to_string(),
                after: "r1bqk1nr/ppp2ppp/2np4/b3p3/2BPP3/2P2N2/P4PPP/RNBQ1RK1 b kq - 0 3"
                    .to_string(),
                is_castle: false,
                is_en_passant: false,
                captured: None,
                promotion: None,
            },
        ];

        pretty_assertions::assert_eq!(moves, chess.history_verbose())
    }
}
