pub mod ascii_tests;
pub mod attackers_tests;
pub mod board_tests;
pub mod castling_rights_tests;
pub mod comments_test;
pub mod fen_tests;
pub mod find_divergence_test;
pub mod find_piece_tests;
pub mod headers_tests;
pub mod history_tests;
pub mod is_promotion_tests;
pub mod load_pgn_tests;
pub mod move_tests;
pub mod move_turn_at_tests;
pub mod native_tests;
mod pgn_tests;
pub mod san_tests;
pub mod square_color_tests;
pub mod undo_move_test;
pub mod put_tests;
mod legal_moves_test;
