use serde::{Deserialize, Serialize};
use strum::{Display, EnumString, IntoStaticStr};

// copy of a shakmaty's Square enum but with derived tsify types
#[rustfmt::skip]
#[derive(tsify::Tsify, Serialize, Deserialize, Debug, Display, EnumString, IntoStaticStr, PartialEq, Eq, Clone)]
#[tsify(into_wasm_abi, from_wasm_abi)]
#[serde(rename_all = "camelCase")]
#[strum(serialize_all = "camelCase")]
pub enum SquareStr {
    A1 = 1, B1, C1, D1, E1, F1, G1, H1,
    A2, B2, C2, D2, E2, F2, G2, H2,
    A3, B3, C3, D3, E3, F3, G3, H3,
    A4, B4, C4, D4, E4, F4, G4, H4,
    A5, B5, C5, D5, E5, F5, G5, H5,
    A6, B6, C6, D6, E6, F6, G6, H6,
    A7, B7, C7, D7, E7, F7, G7, H7,
    A8, B8, C8, D8, E8, F8, G8, H8,
}

// bruh
impl SquareStr {
    pub fn from_shakmaty_sq(square: &shakmaty::Square) -> Self {
        match square {
            shakmaty::Square::A1 => SquareStr::A1,
            shakmaty::Square::B1 => SquareStr::B1,
            shakmaty::Square::C1 => SquareStr::C1,
            shakmaty::Square::D1 => SquareStr::D1,
            shakmaty::Square::E1 => SquareStr::E1,
            shakmaty::Square::F1 => SquareStr::F1,
            shakmaty::Square::G1 => SquareStr::G1,
            shakmaty::Square::H1 => SquareStr::H1,
            shakmaty::Square::A2 => SquareStr::A2,
            shakmaty::Square::B2 => SquareStr::B2,
            shakmaty::Square::C2 => SquareStr::C2,
            shakmaty::Square::D2 => SquareStr::D2,
            shakmaty::Square::E2 => SquareStr::E2,
            shakmaty::Square::F2 => SquareStr::F2,
            shakmaty::Square::G2 => SquareStr::G2,
            shakmaty::Square::H2 => SquareStr::H2,
            shakmaty::Square::A3 => SquareStr::A3,
            shakmaty::Square::B3 => SquareStr::B3,
            shakmaty::Square::C3 => SquareStr::C3,
            shakmaty::Square::D3 => SquareStr::D3,
            shakmaty::Square::E3 => SquareStr::E3,
            shakmaty::Square::F3 => SquareStr::F3,
            shakmaty::Square::G3 => SquareStr::G3,
            shakmaty::Square::H3 => SquareStr::H3,
            shakmaty::Square::A4 => SquareStr::A4,
            shakmaty::Square::B4 => SquareStr::B4,
            shakmaty::Square::C4 => SquareStr::C4,
            shakmaty::Square::D4 => SquareStr::D4,
            shakmaty::Square::E4 => SquareStr::E4,
            shakmaty::Square::F4 => SquareStr::F4,
            shakmaty::Square::G4 => SquareStr::G4,
            shakmaty::Square::H4 => SquareStr::H4,
            shakmaty::Square::A5 => SquareStr::A5,
            shakmaty::Square::B5 => SquareStr::B5,
            shakmaty::Square::C5 => SquareStr::C5,
            shakmaty::Square::D5 => SquareStr::D5,
            shakmaty::Square::E5 => SquareStr::E5,
            shakmaty::Square::F5 => SquareStr::F5,
            shakmaty::Square::G5 => SquareStr::G5,
            shakmaty::Square::H5 => SquareStr::H5,
            shakmaty::Square::A6 => SquareStr::A6,
            shakmaty::Square::B6 => SquareStr::B6,
            shakmaty::Square::C6 => SquareStr::C6,
            shakmaty::Square::D6 => SquareStr::D6,
            shakmaty::Square::E6 => SquareStr::E6,
            shakmaty::Square::F6 => SquareStr::F6,
            shakmaty::Square::G6 => SquareStr::G6,
            shakmaty::Square::H6 => SquareStr::H6,
            shakmaty::Square::A7 => SquareStr::A7,
            shakmaty::Square::B7 => SquareStr::B7,
            shakmaty::Square::C7 => SquareStr::C7,
            shakmaty::Square::D7 => SquareStr::D7,
            shakmaty::Square::E7 => SquareStr::E7,
            shakmaty::Square::F7 => SquareStr::F7,
            shakmaty::Square::G7 => SquareStr::G7,
            shakmaty::Square::H7 => SquareStr::H7,
            shakmaty::Square::A8 => SquareStr::A8,
            shakmaty::Square::B8 => SquareStr::B8,
            shakmaty::Square::C8 => SquareStr::C8,
            shakmaty::Square::D8 => SquareStr::D8,
            shakmaty::Square::E8 => SquareStr::E8,
            shakmaty::Square::F8 => SquareStr::F8,
            shakmaty::Square::G8 => SquareStr::G8,
            shakmaty::Square::H8 => SquareStr::H8,
        }
    }

    pub fn to_shakmaty_sq(&self) -> shakmaty::Square {
        match &self {
            SquareStr::A1 => shakmaty::Square::A1,
            SquareStr::B1 => shakmaty::Square::B1,
            SquareStr::C1 => shakmaty::Square::C1,
            SquareStr::D1 => shakmaty::Square::D1,
            SquareStr::E1 => shakmaty::Square::E1,
            SquareStr::F1 => shakmaty::Square::F1,
            SquareStr::G1 => shakmaty::Square::G1,
            SquareStr::H1 => shakmaty::Square::H1,
            SquareStr::A2 => shakmaty::Square::A2,
            SquareStr::B2 => shakmaty::Square::B2,
            SquareStr::C2 => shakmaty::Square::C2,
            SquareStr::D2 => shakmaty::Square::D2,
            SquareStr::E2 => shakmaty::Square::E2,
            SquareStr::F2 => shakmaty::Square::F2,
            SquareStr::G2 => shakmaty::Square::G2,
            SquareStr::H2 => shakmaty::Square::H2,
            SquareStr::A3 => shakmaty::Square::A3,
            SquareStr::B3 => shakmaty::Square::B3,
            SquareStr::C3 => shakmaty::Square::C3,
            SquareStr::D3 => shakmaty::Square::D3,
            SquareStr::E3 => shakmaty::Square::E3,
            SquareStr::F3 => shakmaty::Square::F3,
            SquareStr::G3 => shakmaty::Square::G3,
            SquareStr::H3 => shakmaty::Square::H3,
            SquareStr::A4 => shakmaty::Square::A4,
            SquareStr::B4 => shakmaty::Square::B4,
            SquareStr::C4 => shakmaty::Square::C4,
            SquareStr::D4 => shakmaty::Square::D4,
            SquareStr::E4 => shakmaty::Square::E4,
            SquareStr::F4 => shakmaty::Square::F4,
            SquareStr::G4 => shakmaty::Square::G4,
            SquareStr::H4 => shakmaty::Square::H4,
            SquareStr::A5 => shakmaty::Square::A5,
            SquareStr::B5 => shakmaty::Square::B5,
            SquareStr::C5 => shakmaty::Square::C5,
            SquareStr::D5 => shakmaty::Square::D5,
            SquareStr::E5 => shakmaty::Square::E5,
            SquareStr::F5 => shakmaty::Square::F5,
            SquareStr::G5 => shakmaty::Square::G5,
            SquareStr::H5 => shakmaty::Square::H5,
            SquareStr::A6 => shakmaty::Square::A6,
            SquareStr::B6 => shakmaty::Square::B6,
            SquareStr::C6 => shakmaty::Square::C6,
            SquareStr::D6 => shakmaty::Square::D6,
            SquareStr::E6 => shakmaty::Square::E6,
            SquareStr::F6 => shakmaty::Square::F6,
            SquareStr::G6 => shakmaty::Square::G6,
            SquareStr::H6 => shakmaty::Square::H6,
            SquareStr::A7 => shakmaty::Square::A7,
            SquareStr::B7 => shakmaty::Square::B7,
            SquareStr::C7 => shakmaty::Square::C7,
            SquareStr::D7 => shakmaty::Square::D7,
            SquareStr::E7 => shakmaty::Square::E7,
            SquareStr::F7 => shakmaty::Square::F7,
            SquareStr::G7 => shakmaty::Square::G7,
            SquareStr::H7 => shakmaty::Square::H7,
            SquareStr::A8 => shakmaty::Square::A8,
            SquareStr::B8 => shakmaty::Square::B8,
            SquareStr::C8 => shakmaty::Square::C8,
            SquareStr::D8 => shakmaty::Square::D8,
            SquareStr::E8 => shakmaty::Square::E8,
            SquareStr::F8 => shakmaty::Square::F8,
            SquareStr::G8 => shakmaty::Square::G8,
            SquareStr::H8 => shakmaty::Square::H8,
        }
    }

    pub fn as_str(&self) -> &'static str {
        match &self {
            SquareStr::A1 => "a1",
            SquareStr::B1 => "b1",
            SquareStr::C1 => "c1",
            SquareStr::D1 => "d1",
            SquareStr::E1 => "e1",
            SquareStr::F1 => "f1",
            SquareStr::G1 => "g1",
            SquareStr::H1 => "h1",
            SquareStr::A2 => "a2",
            SquareStr::B2 => "b2",
            SquareStr::C2 => "c2",
            SquareStr::D2 => "d2",
            SquareStr::E2 => "e2",
            SquareStr::F2 => "f2",
            SquareStr::G2 => "g2",
            SquareStr::H2 => "h2",
            SquareStr::A3 => "a3",
            SquareStr::B3 => "b3",
            SquareStr::C3 => "c3",
            SquareStr::D3 => "d3",
            SquareStr::E3 => "e3",
            SquareStr::F3 => "f3",
            SquareStr::G3 => "g3",
            SquareStr::H3 => "h3",
            SquareStr::A4 => "a4",
            SquareStr::B4 => "b4",
            SquareStr::C4 => "c4",
            SquareStr::D4 => "d4",
            SquareStr::E4 => "e4",
            SquareStr::F4 => "f4",
            SquareStr::G4 => "g4",
            SquareStr::H4 => "h4",
            SquareStr::A5 => "a5",
            SquareStr::B5 => "b5",
            SquareStr::C5 => "c5",
            SquareStr::D5 => "d5",
            SquareStr::E5 => "e5",
            SquareStr::F5 => "f5",
            SquareStr::G5 => "g5",
            SquareStr::H5 => "h5",
            SquareStr::A6 => "a6",
            SquareStr::B6 => "b6",
            SquareStr::C6 => "c6",
            SquareStr::D6 => "d6",
            SquareStr::E6 => "e6",
            SquareStr::F6 => "f6",
            SquareStr::G6 => "g6",
            SquareStr::H6 => "h6",
            SquareStr::A7 => "a7",
            SquareStr::B7 => "b7",
            SquareStr::C7 => "c7",
            SquareStr::D7 => "d7",
            SquareStr::E7 => "e7",
            SquareStr::F7 => "f7",
            SquareStr::G7 => "g7",
            SquareStr::H7 => "h7",
            SquareStr::A8 => "a8",
            SquareStr::B8 => "b8",
            SquareStr::C8 => "c8",
            SquareStr::D8 => "d8",
            SquareStr::E8 => "e8",
            SquareStr::F8 => "f8",
            SquareStr::G8 => "g8",
            SquareStr::H8 => "h8",
        }
    }
}
